services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data
    networks:
      - tanstack-start-boiler-network

networks:
  tanstack-start-boiler-network:
    driver: bridge
